In [9]:
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn import model_selection


In [10]:
train_data = pd.read_csv("0000000000013600_training_train.csv", delimiter = ",")
train_data.head()

age     sex     bmi  children smoker     region      charges
0   51  female  33.915         0     no  northeast   9866.30485
1   55    male  32.775         0     no  northwest  10601.63225
2   18  female  39.160         0     no  southeast   1633.04440
3   27  female  31.400         0    yes  southwest  34838.87300
4   18    male  38.170         0    yes  southeast  36307.79830

In [11]:
test_data = pd.read_csv("0000000000013600_test_test.csv", delimiter = ",")
test_data.columns = ['age','sex','bmi','children','smoker','region']
test_data.head()

age     sex    bmi  children smoker     region
0   46  female  27.72         1     no  southeast
1   19  female  28.90         0     no  southwest
2   53    male  26.41         2     no  northeast
3   18    male  41.14         0     no  southeast
4   63  female  25.08         0     no  northwest

In [12]:
train_data['sex'].unique(), train_data['region'].unique()

(array(['female', 'male'], dtype=object),
 array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object))

In [13]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
  
train_data['sex']= label_encoder.fit_transform(train_data['sex'])
train_data['region']= label_encoder.fit_transform(train_data['region'])
train_data['smoker']= label_encoder.fit_transform(train_data['smoker'])
  
test_data['sex'] = label_encoder.fit_transform(test_data['sex'])
test_data['region']= label_encoder.fit_transform(test_data['region'])
test_data['smoker']= label_encoder.fit_transform(test_data['smoker'])

train_data['sex'].unique(), train_data['region'].unique(), train_data['smoker'].unique(),test_data['sex'].unique(), test_data['region'].unique(), test_data['smoker'].unique()

(array([0, 1]),
 array([0, 1, 2, 3]),
 array([0, 1]),
 array([0, 1]),
 array([2, 3, 0, 1]),
 array([0, 1]))

In [14]:
train = train_data.to_numpy()
#train, test

In [30]:
X_train = train[:, :-1]
print(X_train.shape)
Y_train = train[:, -1]
print(Y_train.shape)

(936, 6)
(936,)


In [31]:
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[ 0.83942311, -1.01074145,  0.53161413, -0.91474534, -0.50800051,
        -1.3751838 ],
       [ 1.12541821,  0.98937271,  0.34389248, -0.91474534, -0.50800051,
        -0.47127085],
       [-1.52003645, -1.01074145,  1.39529841, -0.91474534, -0.50800051,
         0.43264209],
       ...,
       [-1.30554012,  0.98937271, -0.8137244 ,  0.74778211, -0.50800051,
        -1.3751838 ],
       [-0.66205115, -1.01074145, -0.3757072 , -0.08348161, -0.50800051,
        -0.47127085],
       [-0.30455728,  0.98937271, -0.50661836, -0.08348161, -0.50800051,
         0.43264209]])

In [17]:
# generic gd

def step_gradient(X, Y, learning_rate, m):
    m_slope = np.zeros(len(X[0]))
    M = len(X)
    for i in range(M):
        x = X[i]
        y = Y[i]
        for j in range(len(x)):
            m_slope[j] += -(2 / M) * (y - sum(m * x)) * x[j]
    new_m = m - learning_rate * m_slope
    return new_m

In [18]:
def gd(X, Y, learning_rate, n_iterations):
    m = np.zeros(len(X[0]))
    for i in range(n_iterations):
        m = step_gradient(X, Y, learning_rate, m)
        print(i, "Cost : ", cost(X, Y, m))
    return m

In [19]:
def cost(X, Y, m):
    tot_cost = 0
    M = len(X)
    for i in range(M):
        tot_cost += (1 / M) * ((Y[i] - (m * x[i]).sum()) ** 2)
    return tot_cost

In [24]:
def run(x, y):

    learning_rate = 0.00099
    n_iterations = 20

    x = np.append(x, np.ones(len(x)).reshape(-1, 1),axis = 1) 
    m = gd(x, y, learning_rate, n_iterations)
    
    print(m)
    return m

In [33]:
X_train

array([[ 0.83942311, -1.01074145,  0.53161413, -0.91474534, -0.50800051,
        -1.3751838 ],
       [ 1.12541821,  0.98937271,  0.34389248, -0.91474534, -0.50800051,
        -0.47127085],
       [-1.52003645, -1.01074145,  1.39529841, -0.91474534, -0.50800051,
         0.43264209],
       ...,
       [-1.30554012,  0.98937271, -0.8137244 ,  0.74778211, -0.50800051,
        -1.3751838 ],
       [-0.66205115, -1.01074145, -0.3757072 , -0.08348161, -0.50800051,
        -0.47127085],
       [-0.30455728,  0.98937271, -0.50661836, -0.08348161, -0.50800051,
         0.43264209]])

In [32]:
run(X_train, Y_train)

ValueError: operands could not be broadcast together with shapes (7,) (5,) 

In [ ]:
def run():
    #data = X
    learning_rate = 0.00099
    n_iterations = 10
    x = X_test
    x = np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)
    y = X_test[:, -1:] 
    m = gd(x, y, learning_rate, n_iterations)
    print(m)

In [ ]:
run()

In [ ]:
Y_pred = []
x = X_test
x = np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)
for i in x:
    Y_pred.append(sum(m * i))

for i in Y_pred:
    print(i)

Y_pred = np.array(Y_pred)

Y_pred

In [ ]:
np.savetxt(X = Y_pred, fname = "Predicted.csv", delimiter = ",", fmt = "%.5f")